apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab1-gatekeeper-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/open-policy-agent/gatekeeper.git
    targetRevision: v3.13.0
    path: deploy/gatekeeper.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
