apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab1-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nguyenthihuyhoang/hoang-aws-accelerator-p2.git'
    targetRevision: HEAD
    path: 'W10/lab1/rbac'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
