apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: w9-email
  namespace: monitoring
  labels:
    alertmanagerConfig: w9-email
spec:
  route:
    receiver: mentor-email
    groupBy:
      - alertname
      - namespace
    matchers:
      - name: severity
        value: critical
        matchType: "="
  receivers:
    - name: mentor-email
      emailConfigs:
        - to: mentor@example.com
          from: w9@example.com
          smarthost: smtp.example.com:587
          requireTLS: true
          sendResolved: true
          authUsername: w9@example.com
          authPassword:
            name: alertmanager-smtp
            key: password
