apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: w9-email
  namespace: monitoring
  labels:
    alertmanagerConfig: w9-email
spec:
  route:
    receiver: mentor-email
    groupBy:
      - alertname
      - namespace
    matchers:
      - name: severity
        value: critical
        matchType: "="
  receivers:
    - name: mentor-email
      emailConfigs:
        - to: nguyenthihuyhoang1104@gmail.com
          from: hoangnth.22git@vku.udn.vn
          smarthost: smtp.gmail.com:587
          requireTLS: true
          sendResolved: true
          authUsername: hoangnth.22git@vku.udn.vn
          authPassword:
            name: alertmanager-smtp
            key: tvmmxqzktsiqtvkf
