apiVersion: v1
kind: Pod
metadata:
  name: test-valid-pod
  namespace: demo
spec:
  containers:
  - name: test-app
    image: ghcr.io/nguyenthihuyhoang/app:1.0.0
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    securityContext:
      runAsUser: 1000
